module.exports = {
  "shortcodes": {
    "format": "N",
    "suffix1": "R",
    "suffix2": "T",
    "suffix3": "Q",
    "adjective": "Y",
    "noun": "U",
    "clone": "G",
    "mechanics": "E",
    "theme": "A",
    "features": "P",
    "place": "L",
    "character": "O",
    "voiceactor": "B",
    "musician": "Z"
  },
  "format": [
    "{{adjective}} {{noun}} {{suffix1}}",
    "a clone of {{clone}} {{suffix2}}",
    "an exploration of {{theme}} {{suffix3}}"
  ],
  "suffix1": [
    "that is basically a clone of {{clone}}",
    "with the mechanics of {{mechanics}}",
    "that borrows design from {{mechanics}}",
    "that also features {{features}}",
    "that explores the theme of {{theme}}",
    "centered around {{theme}}",
    "that comes with {{features}}",
    "set in {{place}}",
    "that takes place in {{place}}",
  ],
  "suffix2": [
    "but set in {{place}}",
    "but with the mechanics of {{mechanics}}",
    "but with {{features}}",
    "that digs into the theme of {{theme}}",
    "that is also {{adjective}} {{noun}}"
  ],
  "suffix3": [
    "in the form of {{adjective}} {{noun}}",
    "that plays out as {{adjective}} {{noun}}",
    "that manifests as {{adjective}} {{noun}}",
    "as a {{noun}} with {{features}}",
    "set in {{place}} as a {{noun}}"
  ],
  "adjective": [
    "a sports",
    "a genre defining",
    "a procedurally generated",
    "a cel-shaded",
    "a metroidvania-style",
    "a rougelike",
    "a roguelike-like",
    "an anime-styled",
    "a realistic",
    "a military",
    "a gritty",
    "a colorful",
    "a throwback",
    "a dancing",
    "a retro pixel",
    "a party game",
    "a mechanically intense",
    "a couch co-op",
    "a massively online multiplayer",
    "a online multiplayer",
    "a multi-user",
    "a social",
    "a mobile",
    "a online co-op",
    "a real-time",
    "a turn based",
    "an asymmetrical",
    "a cartoony",
    "a remade",
    "an arcade",
    "an indie",
    "a triple-A",
    "a space",
    "a science fiction",
    "a fantasy",
    "a high fantasy",
    "an open world",
    "a extremely linear",
    "a rhythm",
    "a music",
    "a fast food promotional",
    "a free-to-play",
    "a well-written",
    "an extremely boring"
  ],
  "noun": [
    "game",
    "first person shooter",
    "2D platformer",
    "third person shooter",
    "RPG",
    "Japanese RPG",
    "western RPG",
    "simulation",
    "sports game",
    "3D platformer",
    "collect-a-thon",
    "metroidvania",
    "MOBA",
    "tower defense game",
    "strategy game",
    "survival game",
    "crafting game",
    "PC game",
    "visual novel",
    "dating simulator",
    "shoot-em-up",
    "card game",
    "board game",
    "fashion simulator",
    "clicker game",
    "dungeon crawler",
    "racing game",
    "fighting game",
    "brawler",
    "kart game",
    "murder simulator",
    "beach volleyball game"
  ],
  "clone": [
    "Gauntlet",
    "Ms. Pac-Man",
    "Dead Rising",
    "Mario is Missing!",
    "Final Fantasy V",
    "Persona 4",
    "Resident Evil: Code Veronica",
    "DOTA 2",
    "Grand Theft Auto 3",
    "Earth Defense Force",
    "Super Mario World",
    "Star Fox",
    "Altered Beast",
    "River City Ransom",
    "Soulcalibur II",
    "The Last of Us",
    "Fez",
    "World of Warcraft",
    "Terraria",
    "No Man’s Sky",
    "Dance Dance Revolution",
    "God Hand",
    "Saints Row 3",
    "Space Channel 5",
    "Bejeweled",
    "Ninja Gaiden",
    "Spec Ops: The Line",
    "Total War: Rome II",
    "Don't Starve",
    "Stardew Valley",
    "Call of Duty: World at War",
    "Gears of War 2",
    "Halo: ODST",
    "Ninety-Nine Nights II",
    "Vegas Dreams",
    "Garry's Mod",
    "DayZ",
    "Sanctum",
    "Skibi's Castle TD",
    "Recettear: An Item Shop's Tale",
    "Cruisin' USA",
    "Star Wars: Shadow of the Empire",
    "Bayonetta",
    "WARFACE",
    "Tribes 2",
    "Journey",
    "Beyond Good and Evil",
    "Tony Hawk's Project 8",
    "Words With Friends",
    "Draw Something",
    "Catherine",
    "Silent Hill 3",
    "Everyday Shooter",
    "LOOM",
    "Heavenly Sword",
    "Commander Keen"
  ],
  "mechanics": [
    "Dark Souls",
    "Burnout Paradise",
    "Assassin's Creed",
    "NBA Jam",
    "Mortal Kombat",
    "SNK vs Capcom 2",
    "Portal",
    "Geometry Wars: Retro Evolved 2",
    "Borderlands",
    "Diablo",
    "Noby Noby Boy",
    "Track and Field",
    "Kings Quest V",
    "Leisure Suit Larry",
    "Rez",
    "Ikaruga",
    "Rocket League",
    "Mavis Beacon Teaches Typing",
    "Minecraft",
    "Octodad",
    "Final Fantasy XI",
    "Nights: Into Dreams",
    "Jet Set Radio",
    "Crazy Taxi",
    "Time Crisis",
    "Osu!",
    "Candy Crush",
    "Peggle",
    "Tom Clancy's Splinter Cell",
    "The 7th Guest",
    "Maniac Mansion",
    "Titanfall",
    "Diablo III",
    "Gone Home",
    "Secret of Mana",
    "ToeJam & Earl in Panic on Funkotron",
    "Left 4 Dead 2",
    "Papers, Please",
    "Princess Maker II",
    "X-Change",
    "Her Story",
    "World of Goo",
    "Mischief Makers",
    "Blast Corps",
    "Jet Force Gemini",
    "Star Wars Episode I: Racer",
    "Pokemon Puzzle League",
    "Mirror's Edge",
    "WWF No Mercy",
    "Conker's Bad Fur Day",
    "Flappy Bird",
    "Kim Kardashian: Hollywood",
    "Scribblenauts",
    "Hatoful Boyfriend",
    "Katamari Damacy",
    "P.T.",
    "Fear Effect 2: Retro Helix"
  ], 

  "theme": [
    "loss",
    "suffering",
    "being in the closet",
    "seduction",
    "love",
    "romance",
    "intense sexual experiences",
    "masturbation",
    "fear",
    "betrayal",
    "revenge",
    "Jurassic Park",
    "themes",
    "words",
    "sound",
    "music",
    "crying",
    "sadness",
    "depression",
    "fragile masculinity",
    "anger",
    "white privilege",
    "frustration",
    "rage",
    "silence",
    "being bored",
    "illumination",
    "sadomasochism",
    "femininity",
    "coming of the closet",
    "death",
    "birth",
    "rebirth",
    "redeath",
    "vengeance",
    "revengeance",
    "magic",
    "tragedy",
    "goth",
    "cute",
    "kawaii",
    "daddy issues",
    "the Oedipus complex",
    "nostalgia",
    "heartbreak"
  ],

  "features": [
    "a cameo from {{character}}",
    "the ability to play as {{character}}",
    "micro transactions",
    "full motion video cutscenes",
    "a song by {{musician}}",
    "a soundtrack by {{musician}}",
    "ten minutes of stand up by Ricky Gervais for seemingly no reason at all",
    "downloadable weapon skins",
    "in-game billboards",
    "120 VR missions",
    "VR support",
    "a fruit ninja mini game",
    "voice acting from {{voiceactor}}",
    "a debug level filled with ducks",
    "a new game+ feature",
    "an anime tie-in series",
    "a 90-minute live action movie",
    "a series of tie-in novels",
    "an elaborate post-release ARG",
    "an active esports scene",
    "an active mod community",
    "an esports championship that has a $10 M prize pool",
    "an incredibly dumb joke that people will never stop saying",
    "arcade scoring",
    "a coupon for $3 off a frozen pizza",
    "space combat",
    "a pointless vehicle section",
    "a boss run right before the ending",
    "a speed running mode",
    "a vibrant speed running community",
    "exaggerated breast jiggle",
    "an intensity slider",
    "a big head mode",
    "disturbingly realistic sex scenes",
    "an extremely elaborate character creator",
    "that one Goldfinger song",
    "hats",
    "a realistic female character",
    "an Adults Only ESRB rating",
    "a pair of women's panties in the box",
    "a five-part tie-in comic",
    "four hours of in-game cutscenes",
    "an extremly long and boring tutorial",
    "unskippable custcenes",
    "awful camera controls",
    "frustrating jumping puzzles",
    "a cute animal sidekick",
    "a bug that destroys saves",
    "a secret achievement that will never be unlocked",
    "over 100 different endings",
    "an ending that everyone on the internet hates",
    "an annoying AI companion",
    "a subtle gay subtext",
    "an extremely pronounced gay subtext",
    "over 200,000 words",
    "Facebook integration",
    "hidden collectables that unlock a secret movie",
    "the ability to put a photo of your face on a character",
    "a boss run mode",
    "a live-action movie adaptation for some reason",
    "an Amiibo",
    "an interlude where the characters go to the beach"
  ],
  "place": [
    "a high-school",
    "an office",
    "a college",
    "a private boarding school",
    "a mountaintop village",
    "a rural farming village",
    "a warzone",
    "New York City",
    "Paris",
    "Canada",
    "Las Vegas",
    "Monaco",
    "London",
    "a fantasy world",
    "a space station",
    "a starship",
    "ancient Greece",
    "Japan",
    "Tokyo",
    "Hong Kong"
  ],
  "character": [
    "Mario",
    "Sonic the Hedgehog",
    "Crash Bandicoot",
    "Yoshi",
    "Donkey Kong",
    "Lara Croft",
    "Peter Molyneux",
    "Hideo Kojima",
    "GLA-DOS",
    "the Soldier from TF2",
    "D-VA",
    "literally Chris Traeger",
    "Sailor Moon",
    "Link",
    "Argo the Horse",
    "Sol Badguy",
    "Captain Falcon",
    "the box from Metal Gear Solid",
    "The Final Pam"
  ],

  "voiceactor": [
    "Troy Baker",
    "Nolan North",
    "Steven Blum",
    "Jennifer Hale",
    "Laura Bailey",
    "Donald Trump",
    "Felicia Day",
    "Ikue Otani",
    "Kotono Mitsuishi",
    "Jennifer Garner",
    "Ellen Page",
    "Keven Spacey",
    "that synthesizer therapist program from the 80s",
    "Ashly Burch",
    "Sean Bean",
    "Patrick Stewart",
    "Mark Hamill",
    "Janet Varney",
    "J.K. Simmons",
    "Paul F. Tompkins"
  ],

  "musician": [
    "Yoko Kanno",
    "Danny Elfman",
    "Anamanaguchi",
    "Jonathan Coulton",
    "Florence + The Machine",
    "Sleater-Kinney",
    "Neko Case",
    "Veruca Salt",
    "The Star Wars cantina band",
    "Daisuke Ishiwatari",
    "Beyoncé",
    "The Roots",
    "Patti Smith",
    "Vonda Shepard",
    "Akira Yamaoka",
    "Hans Zimmer",
    "Austin Wintory",
    "Nobuo Uematsu",
    "The Offspring",
    "Bad Religion"
  ]
};
